### ISSUE TITLE
Valid Email Addresses with `$` are being rejected during account creation

### ISSUE THREAD

**Issue by Lonniebiz** [stocknear/backend#9]
I already submitted the details of this to the client-side project here:
https://github.com/stocknear/frontend/issues/16

Since email validation may occur on both the client and server side, I'm linking the issue here too (to be thorough). See details at the link above.

**Comment by MuslemRahimi** [comment]
I’ve chosen not to include the "$" symbol in my database schema due to security concerns. It can introduce vulnerabilities, especially with regard to SQL injection, if not carefully managed.
